### PR TITLE
website facelift

### PR DESCRIPTION
**Pull request by ResidentDelinquent**
ngl everything is simply superior what can i say

heavy refactoring done and dusted because I'm just that guy

huge if real, massive if true

fr fr

### CODE REVIEW

**Comment by Sid722** [comment]
I'm running it locally and running into issues. The navbar and the footer have completely disappeared for me. Also, a lot of the formatting is gone.

**Comment by ResidentDelinquent** [comment]
same just happened on my side as well! I'm guessing something is making the <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script> not work on those pages, maybe that site doesn't work anymore?

**Comment by ResidentDelinquent** [comment]
yeah all the stuff that disappeared have to do with jquery. something has definitely changed with that, but I don't know what

**Comment by ResidentDelinquent** [comment]
issue should be fixed now! apparently a directory when missing, but it was an easy fix thanks to the refactoring

**Pull request merged**
